# Generated by Django 2.0 on 2017-12-15 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('rentid', models.AutoField(primary_key=True, serialize=False)),
                ('renteddate', models.DateTimeField(default=datetime.datetime.now)),
                ('totalamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haspenalty', models.BooleanField(default=False)),
                ('delivereddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='rentmovies',
            fields=[
                ('rentmoviesid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rentalprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rentmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.movie'),
        ),
        migrations.AddField(
            model_name='rentmovies',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.rent'),
        ),
    ]
