# Generated by Django 2.0 on 2017-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171214_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='delivereddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
