# Generated by Django 2.0 on 2017-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171214_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='inprocess',
            field=models.BooleanField(default=True),
        ),
    ]
