# Generated by Django 2.0 on 2017-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rent_inprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='renteddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
