# Generated by Django 2.0 on 2017-12-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171215_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='renteddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
